### ISSUE TITLE
Tarjan's misses lower level strongConnects

### ISSUE THREAD

**Issue by awfulstew** [1123/johnson#1]
As implemented currently, Tarjan's will only add components to the top-level result (the list in the function tarjan()).  This is a problem because we can encounter strong components on lower level calls to strongConnect and these components will just get added to result, returned and then discarded since the recursive call to strongConnect in the function itself does nothing with its return.

To fix this, move the declaration of List<List<NodeType>> result to above the for-loop in strongConnect and then change line 61 from reading "strongConnect(w)" to "result.addAll(strongConnect(w))" so that the lower level strongly connected components get added to the final top-level result list.

**Comment by blinse** [comment]
Thanks for the feedback. This is very much appreciated. I will have a look. Would you mind to submit a pull request or a test case that makes the issue absolutely clear?

Are you saying this is a performance issue or does it make the implementation incorrect? For the latter, I would like to add a test case that makes sure this is fixed.

**Comment by blinse** [comment]
Hi stewarta,

I think I got your point. Pushed a fix. Seems like a test case is still needed to ensure that this is fixed.

Thanks!

**Comment by 1123** [comment]
thanks. Merged your pull request. Closing this issue.

**Comment by awfulstew** [comment]
Glad I could help. It was something I only noticed because I have been running lots of randomly generated graph through the code for testing. Thanks for putting the algorithm up in Java in the first place.
