### ISSUE TITLE
No license specified

### ISSUE THREAD

**Issue by ap0llo** [1123/johnson#3]
I would loke to reuse your implementations of the Johnson and Trajan algorithms in a project of mine.
It would be helpful if you specified a license for you code (Preferrably a permissive license like the MIT-License)

**Comment by 1123** [comment]
Thanks for your feedback. Yes, would Apache 2 license work for you?

**Comment by ap0llo** [comment]
Yes, Apache License would be fine, thanks

**Comment by 1123** [comment]
Done.

**Comment by ap0llo** [comment]
Thank you!

**Comment by 1123** [comment]
welcome. Glad I could help.
